version: '2.1'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./samples/mysql.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    build:
      context: docker/mongo
    environment:
      MONGO_INITDB_DATABASE: test
    ports:
      - '27017:27017'

  nats:
    image: nats:latest
    restart: always
    container_name: nats
    ports:
      - '4222:4222'

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    container_name: rabbitmq
    ports:
      - '5672:5672'

  postgres:
    image: library/postgres:11.4
    restart: always
    ports:
      - "5432:5432"
    environment:
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: test
    volumes:
      - ./samples/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql

  ssh:
    build:
      context: docker/ssh
      args:
        SSH_MASTER_USER: user
        SSH_MASTER_PASS: user
    ports:
      - "2222:22"

  consul-agent-1: &consul-agent
    image: consul:latest
    container_name: consul-agent-1
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent
    container_name: consul-agent-2

  consul-agent-3:
    <<: *consul-agent
    container_name: consul-agent-3

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"
    container_name: consul-server-1

  consul-server-2:
    <<: *consul-server
    container_name: consul-server-2

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"
    container_name: consul-server-bootstrap
  etcd1:
    image: quay.io/coreos/etcd:v3.2.5
    networks:
      - etcd
    ports:
      - 23791:2379
      - 23801:2380
    volumes:
      - ./certs/:/srv/
      - /srv/docker/etcd:/etcd-data
    environment:
      ETCD_NAME: node1
      ETCD_DATA_DIR: /etcd-data/etcd1.etcd
      ETCDCTL_API: 3
      ETCD_DEBUG: 1
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd1:2380
      ETCD_INITIAL_CLUSTER: node3=http://etcd3:2380,node1=http://etcd1:2380,node2=http://etcd2:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd1:2379
  etcd2:
    image: quay.io/coreos/etcd:v3.2.5
    networks:
      - etcd
    ports:
      - 23792:2379
      - 23802:2380
    volumes:
      - ./certs/:/srv/
      - /srv/docker/etcd:/etcd-data
    environment:
      ETCD_NAME: node2
      ETCD_DATA_DIR: /etcd-data/etcd2.etcd
      ETCDCTL_API: 3
      ETCD_DEBUG: 1
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd2:2380
      ETCD_INITIAL_CLUSTER: node3=http://etcd3:2380,node1=http://etcd1:2380,node2=http://etcd2:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd2:2379
  etcd3:
    image: quay.io/coreos/etcd:v3.2.5
    networks:
      - etcd
    ports:
      - 23793:2379
      - 23803:2380
    volumes:
      - ./certs/:/srv/
      - /srv/docker/etcd:/etcd-data
    environment:
      ETCD_NAME: node3
      ETCD_DATA_DIR: /etcd-data/etcd3.etcd
      ETCDCTL_API: 3
      ETCD_DEBUG: 1
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd3:2380
      ETCD_INITIAL_CLUSTER: node3=http://etcd3:2380,node1=http://etcd1:2380,node2=http://etcd2:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd3:2379

  skydns:
    image: skynetservices/skydns
    networks:
      - etcd
    ports:
      - "5354:5354"
      - "5354:5354/udp"

    environment:
      ETCD_MACHINES: http://etcd1:2379

networks:
  etcd:
  consul-demo:
