version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./samples/mysql.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    build:
      context: docker/mongo
    environment:
      MONGO_INITDB_DATABASE: test
    ports:
      - '27017:27017'
