version: '2.1'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./samples/mysql.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    build:
      context: docker/mongo
    environment:
      MONGO_INITDB_DATABASE: test
    ports:
      - '27017:27017'

  nats:
    image: nats:latest
    restart: always
    container_name: nats
    ports:
      - '4222:4222'


  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
    - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
