apiVersion: copybird.org/v1
kind: Backup
metadata:
  name: sample-backup
spec:
  name: sample-backup
  type: "backup"
  cron: "*/1 * * * *"
  input:
    type: mysql
    config:
      dsn: root:root@tcp(localhost:3306)/test
  compress:
    type: gzip
    config:
      level: 2
  output:
    - type: local
      config:
        file: dump.sql.gz
  notifier:
    - type: stdout
