input:
  type: mysql
  config:
    dsn: root:root@tcp(localhost:3306)/test
compress:
  type: gzip
  config:
    level: 1
output:
  - type: local
    config:
      file: dump.sql.gz
notifier:
  - type: stdout